from . import job_board
from . import vendor
from . import res_partner
from . import res_users
from . import tracker_link
from . import hr_recruitment_source
from . import hr_job_tracked_field
from . import hr_job
from . import hr_applicant
from . import hr_applicant_resume_line
from . import hr_job_version_history
from . import hr_applicant_version_history
from . import hr_job_version_history_wizard
from . import hr_applicant_version_history_wizard
from . import job_board_account
